#############################################################################
# Generated by PAGE version 4.1
# in conjunction with Tcl version 8.6
#    Jan. 10, 2014 11:59:08 PM


set vTcl(actual_gui_bg) SystemButtonFace
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) SystemButtonFace
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) SystemButtonFace
set vTcl(analog_color_p) SystemButtonFace
set vTcl(analog_color_m) SystemButtonFace
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top34.tNo44.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top34.tNo44.pg1 
    set site_4_0 $site_4_1
    set site_4_2 .top34.tNo44.pg2 
    set site_4_0 $site_4_2
    set site_5_0 $site_4_0.scr41
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+125+125; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background SystemButtonFace -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x240+426+561; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure TNotebook -background SystemButtonFace
    ttk::style configure TNotebook.Tab -background SystemButtonFace
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled SystemButtonFace selected SystemButtonFace]
    ttk::notebook $top.tNo44 \
        -width 584 -height 226 -takefocus {} 
    vTcl:DefineAlias "$top.tNo44" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame .top34.tNo44.pg0 -background SystemButtonFace
    $top.tNo44 add .top34.tNo44.pg0 \
        -padding 0 -sticky nsew -state normal -text {Start Mining} -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo44.pg0
    ttk::style configure TButton -background SystemButtonFace
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu52 \
        \
        -command {import sys
import subprocess

mine = subprocess.Popen(["/p2pool/run_p2pool.py"])

batfile = "cgminer --url http://192.168.1.217:9332/ --userpass "+str(address)+":123 "+str(flags)""
save = ("/EasyMiner/cgminer", 'w+')
save.write(batfile)
save.close()

p = Popen("batch.bat", cwd=r"C:\Path\to\batchfolder")
stdout, stderr = p.communicate()} \
        -takefocus {} -text {Start Mining} 
    vTcl:DefineAlias "$site_4_0.tBu52" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab53 \
        -activebackground {#ffffff} -activeforeground black \
        -background SystemButtonFace -disabledforeground {#b4b4b4} \
        -foreground {#000000} -highlightcolor black -text {Bitcoin Address:} 
    vTcl:DefineAlias "$site_4_0.lab53" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent54 \
        -background white -disabledforeground {#b4b4b4} -font font11 \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#d8d8d8} -selectforeground black \
        -textvariable address 
    vTcl:DefineAlias "$site_4_0.ent54" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab55 \
        -activebackground {#ffffff} -activeforeground black \
        -background SystemButtonFace -disabledforeground {#b4b4b4} \
        -foreground {#000000} -highlightcolor black -text Flags: 
    vTcl:DefineAlias "$site_4_0.lab55" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#b4b4b4} -font font11 \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#d8d8d8} -selectforeground black \
        -textvariable flags 
    vTcl:DefineAlias "$site_4_0.ent56" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background SystemButtonFace
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu58 \
        -command {print "stop info goes here"} -takefocus {} \
        -text {Stop Mining} 
    vTcl:DefineAlias "$site_4_0.tBu58" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $site_4_0.tPr35 \
        -length 100 -variable bar -value 0.0 
    vTcl:DefineAlias "$site_4_0.tPr35" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa36 \
        -background {#000000} -foreground {#000000} -relief flat \
        -text ______________________________________________________________________________________________________________________________________________________________ 
    vTcl:DefineAlias "$site_4_0.tLa36" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa37 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {Mining info goes here} 
    vTcl:DefineAlias "$site_4_0.tLa37" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tBu52 \
        -in $site_4_0 -x 199 -y 131 -width 76 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_4_0.ent54 \
        -in $site_4_0 -x 110 -y 10 -width 454 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 50 -y 50 -width 514 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tBu58 \
        -in $site_4_0 -x 300 -y 131 -width 76 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tPr35 \
        -in $site_4_0 -x 454 -y 172 -width 120 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa36 \
        -in $site_4_0 -x -108 -y 165 -width 794 -height 1 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa37 \
        -in $site_4_0 -x 10 -y 173 -width 436 -height 19 -anchor nw \
        -bordermode ignore 
    frame .top34.tNo44.pg1 -background SystemButtonFace
    $top.tNo44 add .top34.tNo44.pg1 \
        -padding 0 -sticky nsew -state normal -text Info -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo44.pg1
    ttk::label $site_4_1.tLa46 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {Version: Bitcoin x32 Beta + CGMiner} 
    vTcl:DefineAlias "$site_4_1.tLa46" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_1.tLa47 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {Compiled 01/09/2014} 
    vTcl:DefineAlias "$site_4_1.tLa47" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_1.tLa48 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {This software was created by Argutus1 on Reddit.} 
    vTcl:DefineAlias "$site_4_1.tLa48" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_1.tLa49 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {This software may be edited and redistributed, on the condition that this page will not be edited.} 
    vTcl:DefineAlias "$site_4_1.tLa49" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_1.tLa50 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {Donations may be sent to: 13GGffkBfcf8nbfBE2qxnxgpqXAbjEyehF} 
    vTcl:DefineAlias "$site_4_1.tLa50" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_1.tLa51 \
        -background SystemButtonFace -foreground {#000000} -relief flat \
        -text {Bitcoind or qt must be running to use this software. The config file also must have server mode enabled.} 
    vTcl:DefineAlias "$site_4_1.tLa51" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab57 \
        -activebackground {#ffffff} -activeforeground black \
        -background SystemButtonFace -disabledforeground {#b4b4b4} \
        -foreground {#000000} -highlightcolor black \
        -text {EasyMiner uses CGMiner for its mining process, look it up for available flags } 
    vTcl:DefineAlias "$site_4_1.lab57" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.tLa46 \
        -in $site_4_1 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_4_1.tLa47 \
        -in $site_4_1 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_4_1.tLa48 \
        -in $site_4_1 -x 10 -y 80 -anchor nw -bordermode ignore 
    place $site_4_1.tLa49 \
        -in $site_4_1 -x 10 -y 100 -anchor nw -bordermode ignore 
    place $site_4_1.tLa50 \
        -in $site_4_1 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_4_1.tLa51 \
        -in $site_4_1 -x 10 -y 171 -width 576 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab57 \
        -in $site_4_1 -x 10 -y 154 -width 407 -height 21 -anchor nw \
        -bordermode ignore 
    frame .top34.tNo44.pg2 -background SystemButtonFace
    $top.tNo44 add .top34.tNo44.pg2 \
        -padding 0 -sticky nsew -state normal -text {Flag List} -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo44.pg2
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr41 \
        -background SystemButtonFace -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_2.scr41" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    .top34.tNo44.pg2.scr41.01 configure -background white \
        -disabledforeground #b4b4b4 \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightcolor SystemButtonFace \
        -selectbackground #d8d8d8 \
        -selectforeground black \
        -width 10 \
        -listvariable flaglist
    place $site_4_2.scr41 \
        -in $site_4_2 -x 8 -y 8 -width 564 -height 185 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo44 \
        -in $top -x 10 -y 10 -width 584 -height 226 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

